openapi: 3.0.0
info:
  title: Find Wifi API
  version: "0.01"
  description: |-
    # Introduction
    Wi-Fiスポット検索サービスのAPI

    <h2>API一覧</h2>
    <table>
      <thead>
        <th>No.</th><th>Group</th><th>Method</th><th>Path</th><th>API名称</th><th>説明</th>
      </thead>
      <tbody>
        <tr><td>S-1</td><td>Shop</td><td>GET</td><td>/v1/shops</td>
        <td>店舗一覧取得</td><td><b>サイト用</b> Wi-Fi利用可能店舗一覧を取得する。</td></tr>
        <tr><td>S-2</td><td>Shop</td><td>POST</td><td>/v1/shops</td>
        <td>店舗登録</td><td><b>管理用</b> Wi-Fi利用可能店舗を登録する。</td></tr>
        <tr><td>S-3</td><td>Shop</td><td>GET</td><td>/v1/shops/:shop_id</td>
        <td>店舗詳細取得</td><td><b>サイト用</b> Wi-Fi利用可能店舗の詳細情報を取得する。</td></tr>
        <tr><td>S-4</td><td>Shop</td><td>PUT</td><td>/v1/shops/:shop_id</td>
        <td>店舗情報編集</td><td><b>管理用</b> Wi-Fi利用可能店舗の情報を編集する。</td></tr>
        <tr><td>S-5</td><td>Shop</td><td>DELETE</td><td>/v1/shops/:shop_id</td>
        <td>店舗削除</td><td><b>管理用</b> Wi-Fi利用可能店舗を削除する。</td></tr>
        <tr><td>R-1</td><td>Review</td><td>GET</td><td>/v1/reviews</td>
        <td>レビュー一覧取得</td><td><b>サイト用</b> 店舗に投稿されたレビュー一覧を取得する。</td></tr>
        <tr><td>R-2</td><td>Review</td><td>POST</td><td>/v1/reviews</td>
        <td>レビュー投稿</td><td><b>サイト用</b> 店舗にレビューを投稿する。</td></tr>
        <tr><td>R-3</td><td>Review</td><td>PUT</td><td>/v1/reviews/:review_id</td>
        <td>レビュー公開・非公開</td><td><b>管理用</b> レビューの公開・非公開を変更する。</td></tr>
        <tr><td>W-1</td><td>Wi-Fi Service</td><td>GET</td><td>/v1/services</td>
        <td>Wi-Fiサービス一覧取得</td><td><b>管理用</b> Wi-Fiサービス一覧を取得する。</td></tr>
        <tr><td>W-2</td><td>Wi-Fi Service</td><td>POST</td><td>/v1/services</td>
        <td>Wi-Fiサービス登録</td><td><b>管理用</b> Wi-Fiサービスを登録する。</td></tr>
    </table>
servers:
  - url: http://localhost:3000
    description: ローカル
tags:
  - name: Shop
    description: 店舗関連API
  - name: Review
    description: レビュー関連API
x-tagGroups:
  - name: API
    tags:
      - Shop
      - Review

paths:
  /v1/shops:
    # GET /v1/shops 店舗一覧取得API
    get:
      tags:
        - Shop
      summary: 店舗一覧取得
      operationId: getShopList
      description: |-
        Wi-Fi利用可能店舗一覧を取得する。
      x-code-samples:
        - lang: Shell
          label: cURL
          source: |
            curl 'http://localhost:3000/v1/shops?position=xxx&power=true&limit=10&offset=10'
      parameters:
        - name: position
          in: query
          description: 位置情報
          required: true
          schema:
            type: number
            format: 数字
            example: xxx
        - name: wifi_id
          in: query
          description: Wi-Fi ID
          schema:
            type: string
            format: 半角英数字
            example: starbucks_wifi
        - name: power
          in: query
          description: 電源があるかどうか
          schema:
            type: boolean
            format: 真理値
            example: true
        - name: limit
          in: query
          description: リミット(取得件数)
          schema:
            type: number
            format: 数字
            example: 20
        - name: offset
          in: query
          description: オフセット(ページの開始位置)
          schema:
            type: number
            format: 数字
            example: 10
        - name: sort
          in: query
          description: ソート方法
          schema:
            type: string
            format: asc / desc
            example: desc
      responses:
        "200":
          description: 成功時のレスポンス
          content:
            "application/json":
              schema:
                type: object
                required:
                  - shop_list
                  - total
                properties:
                  shop_list:
                    type: array
                    description: 店舗リスト
                    items:
                      type: object
                      required:
                        - shop_id
                        - wifi_id
                        - ssid
                        - name
                        - address
                        - power
                      properties:
                        shop_id:
                          description: 店舗ID
                          type: string
                          format: UUID
                          example: 6aa3b8b5-1b5c-40c7-85cc-1cde056eb4c2
                        wifi_id:
                          description: Wi-Fi ID
                          type: string
                          format: 半角英数字
                          example: starbucks_wifi
                        ssid:
                          description: SSID
                          type: array
                          items:
                            type: string
                            format: 半角英数字
                          example:
                            - at_STARBUCKS_Wi2
                        name:
                          description: 店舗名
                          type: string
                          format: 文字列
                          example: スターバックス渋谷店
                        address:
                          description: 店舗住所
                          type: string
                          format: 文字列
                          example: 東京都渋谷区道玄坂1-1-1
                        power:
                          description: 電源があるかどうか
                          type: boolean
                          format: 真理値
                          example: true
                        average:
                          description: 評価の平均値
                          type: number
                          format: 数値
                          example: 3.50
                  total:
                    description: 店舗総数
                    type: number
                    format: 数字
                    example: 50
        "400":
          description: パラメータ不正
        "500":
          description: システムエラー

  /v1/shops/{shop_id}:
    # GET /v1/shops/:shop_id 店舗詳細取得API
    get:
      tags:
        - Shop
      summary: 店舗詳細取得
      operationId: getShopDetail
      description: |-
        Wi-Fi利用可能店舗の詳細情報を取得する。
      x-code-samples:
        - lang: Shell
          label: cURL
          source: |
            curl 'http://localhost:3000/v1/shops/6aa3b8b5-1b5c-40c7-85cc-1cde056eb4c2'
      parameters:
        - name: shop_id
          in: path
          description: 店舗ID
          required: true
          schema:
            type: string
            format: UUID
            example: 6aa3b8b5-1b5c-40c7-85cc-1cde056eb4c2
      responses:
        "200":
          description: 成功時のレスポンス
          content:
            "application/json":
              schema:
                type: object
                required:
                  - shop_id
                  - wifi_id
                  - ssid
                  - name
                  - address
                  - power
                properties:
                  shop_id:
                    description: 店舗ID
                    type: string
                    format: UUID
                    example: 6aa3b8b5-1b5c-40c7-85cc-1cde056eb4c2
                  wifi_id:
                    description: Wi-Fi ID
                    type: string
                    format: 半角英数字
                    example: starbucks_wifi
                  ssid:
                    description: SSID
                    type: array
                    items:
                      type: string
                      format: 半角英数字
                    example:
                      - at_STARBUCKS_Wi2
                  name:
                    description: 店舗名
                    type: string
                    format: 文字列
                    example: スターバックス渋谷店
                  address:
                    description: 店舗住所
                    type: string
                    format: 文字列
                    example: 東京都渋谷区道玄坂1-1-1
                  power:
                    description: 電源があるかどうか
                    type: boolean
                    format: 真理値
                    example: true
                  average:
                    description: 評価の平均値
                    type: number
                    format: 数値
                    example: 3.50
                  link:
                    description: 公式サイトへのリンク
                    type: string
                    format: URL
                    example: http://xxxxx.com
                  shop_images:
                    description: 店舗画像のURL
                    type: array
                    items:
                      type: string
                      format: URL
                    example:
                      - xxx.png
                      - yyy.png
        "400":
          description: パラメータ不正
        "500":
          description: システムエラー

  /v1/reviews:
    # GET /v1/reviews レビュー一覧取得API
    get:
      tags:
        - Review
      summary: レビュー一覧取得
      operationId: getReviewList
      description: |-
        Wi-Fi利用可能店舗に投稿されたレビューの一覧を取得する。
      x-code-samples:
        - lang: Shell
          label: cURL
          source: |
            curl 'http://localhost:3000/v1/reviews?shop_id=6aa3b8b5-1b5c-40c7-85cc-1cde056eb4c2&limit=10&offset=10'
      parameters:
        - name: shop_id
          in: query
          description: UUID
          required: true
          schema:
            type: number
            format: 数字
            example: 6aa3b8b5-1b5c-40c7-85cc-1cde056eb4c2
        - name: limit
          in: query
          description: リミット(取得件数)
          schema:
            type: number
            format: 数字
            example: 20
        - name: offset
          in: query
          description: オフセット(ページの開始位置)
          schema:
            type: number
            format: 数字
            example: 10
        - name: sort
          in: query
          description: ソート方法
          schema:
            type: string
            format: asc / desc
            example: desc
      responses:
        "200":
          description: 成功時のレスポンス
          content:
            "application/json":
              schema:
                type: object
                required:
                  - review_list
                  - total
                properties:
                  review_list:
                    type: array
                    description: レビューリスト
                    items:
                      type: object
                      required:
                        - review_id
                        - comment
                        - evaluation
                      properties:
                        review_id:
                          description: レビューID
                          type: string
                          format: 半角英数字
                          example: 6aa3b8b5-1b5c-40c7-85cc-1cde056eb4c2
                        comment:
                          description: レビュー本文
                          type: string
                          format: 文字列
                          example: 使いやすい
                        evaluation:
                          description: 評価
                          type: number
                          format: 数値
                          enum: [1,2,3,4,5]
                          example: 5
                  total:
                    description: レビュー総数
                    type: number
                    format: 数字
                    example: 50
        "400":
          description: パラメータ不正
        "500":
          description: システムエラー
  
    # POST /v1/reviews レビュー投稿API
    post:
      tags:
        - Review
      summary: レビュー投稿
      operationId: postReview
      description: |-
        Wi-Fi利用可能店舗にレビューを投稿する。
      x-code-samples:
        - lang: Shell
          label: cURL
          source: |
            curl -X POST 'http://localhost:3000/v1/reviews' \
              -H 'Contents-Type: application/x-www-form-urlencoded' \
              -d 'shop_id=6aa3b8b5-1b5c-40c7-85cc-1cde056eb4c2' \
              -d 'comment=使いやすい' \
              -d 'evaluation=5'
      requestBody:
        content:
          "application/x-www-form-urlencoded":
            schema:
              type: object
              required:
                - shop_id
                - comment
                - evaluation
              properties:
                shop_id:
                  description: 店舗ID
                  type: string
                  format: UUID
                  example: 6aa3b8b5-1b5c-40c7-85cc-1cde056eb4c2
                comment:
                  description: レビュー本文
                  type: string
                  format: 文字列
                  example: 使いやすい
                evaluation:
                  description: 評価
                  type: number
                  format: 数値
                  enum: [1,2,3,4,5]
                  example: 3
      responses:
        "200":
          description: 成功時のレスポンス
          content:
            "application/json":
              schema:
                type: object
                required:
                  - review_id
                properties:
                  review_id:
                    description: レビューID
                    type: string
                    format: 半角英数字
                    example: 6aa3b8b5-1b5c-40c7-85cc-1cde056eb4c2
        "400":
          description: パラメータ不正
        "500":
          description: システムエラー