default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: wifi_map_db
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: db/development.mysql2

test:
  <<: *default
  database: db/test.mysql2

production:
  <<: *default
  database: db/production.mysql2
